### ISSUE TITLE
Kaggle CUDA out of memory

### ISSUE THREAD

**Issue by trongldwork** [yyang181/colormnet#15]
I have tried to use kaggle to train your model with my dataset, but it seem 16gb of Vram from GPU P100 is not enough?
How to optimize your model so that i can train it with 16gb Vram?

```
hyperpara {'benchmark': False, 'no_amp': False, 'davis_root': '/kaggle/input/film-vietnam-war/dataset/dataset/train_set', 'validation_root': '/kaggle/input/film-vietnam-war/dataset/dataset/val_set', 'num_workers': 16, 'key_dim': 64, 'value_dim': 512, 'hidden_dim': 64, 'deep_update_prob': 0.2, 'stages': '2', 'savepath': '/kaggle/working/colormnet/save_path', 's2_batch_size': 1, 's2_iterations': 150000, 's2_finetune': 10000, 's2_steps': [120000], 's2_lr': 2e-05, 's2_num_ref_frames': 3, 's2_num_frames': 8, 's2_start_warm': 20000, 's2_end_warm': 70000, 'gamma': 0.1, 'weight_decay': 0.05, 'load_network': None, 'load_checkpoint': None, 'log_text_interval': 100, 'log_image_interval': 100, 'save_network_interval': 2500, 'save_checkpoint_interval': 5000, 'exp_id': 'DINOv2FeatureV6_LocalAtten_DAVISVidevo_s2', 'debug': False, 'amp': True, 'batch_size': 1, 'iterations': 150000, 'finetune': 10000, 'steps': [120000], 'lr': 2e-05, 'num_ref_frames': 3, 'num_frames': 8, 'start_warm': 20000, 'end_warm': 70000, 'single_object': False, 'num_gpus': 1}
Single object mode: False
Using cache found in /root/.cache/torch/hub/facebookresearch_dinov2_main
model_size 123609281
5 out of 5 videos accepted in /kaggle/input/film-vietnam-war/dataset/dataset/train_set.
DAVIS + Videvo dataset size: 5
Concat dataset size: 5
Renewed with max_skip=5
We approximately use 30000 epochs.
The skip value will change approximately at the following iterations: [15000, 45000, 135000]
Current epoch: 1
starting validation at it: 0
Traceback (most recent call last):
  File "/kaggle/working/colormnet/train.py", line 240, in <module>
    model.do_pass(data, total_iter, val_dataset=val_dataset)
  File "/kaggle/working/colormnet/model/trainer.py", line 343, in do_pass
    current_psnr = self.do_val(it, val_dataset=val_dataset)
  File "/kaggle/working/colormnet/model/trainer.py", line 157, in do_val
    prob = processor.step(rgb, msk, labels, end=(ti==vid_length-1))
  File "/kaggle/working/colormnet/inference/inference_core.py", line 61, in step
    key, shrinkage, selection, f16, f8, f4 = self.network.encode_key(image,
  File "/kaggle/working/colormnet/model/network.py", line 66, in encode_key
    f16, f8, f4 = self.key_encoder(frame)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/kaggle/working/colormnet/model/modules.py", line 193, in forward
    g4 = self.fuse3(self.upsample4(f16_dino), f4)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/kaggle/working/colormnet/model/resnet.py", line 393, in forward
    dnc = self.norm2(dnc)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/kaggle/working/colormnet/model/resnet.py", line 284, in forward
    return LayerNormFunction.apply(x, self.weight, self.bias, self.eps)
  File "/opt/conda/lib/python3.10/site-packages/torch/autograd/function.py", line 574, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/kaggle/working/colormnet/model/resnet.py", line 258, in forward
    y = weight.view(1, C, 1, 1) * y + bias.view(1, C, 1, 1)
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 66.00 MiB. GPU 0 has a total capacity of 14.74 GiB of which 28.12 MiB is free. Process 4776 has 14.71 GiB memory in use. Of the allocated memory 13.83 GiB is allocated by PyTorch, and 427.36 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
[rank0]: Traceback (most recent call last):
[rank0]:   File "/kaggle/working/colormnet/train.py", line 240, in <module>
[rank0]:     model.do_pass(data, total_iter, val_dataset=val_dataset)
[rank0]:   File "/kaggle/working/colormnet/model/trainer.py", line 343, in do_pass
[rank0]:     current_psnr = self.do_val(it, val_dataset=val_dataset)
[rank0]:   File "/kaggle/working/colormnet/model/trainer.py", line 157, in do_val
[rank0]:     prob = processor.step(rgb, msk, labels, end=(ti==vid_length-1))
[rank0]:   File "/kaggle/working/colormnet/inference/inference_core.py", line 61, in step
[rank0]:     key, shrinkage, selection, f16, f8, f4 = self.network.encode_key(image, 
[rank0]:   File "/kaggle/working/colormnet/model/network.py", line 66, in encode_key
[rank0]:     f16, f8, f4 = self.key_encoder(frame)
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/kaggle/working/colormnet/model/modules.py", line 193, in forward
[rank0]:     g4 = self.fuse3(self.upsample4(f16_dino), f4)
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/kaggle/working/colormnet/model/resnet.py", line 393, in forward
[rank0]:     dnc = self.norm2(dnc)
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/kaggle/working/colormnet/model/resnet.py", line 284, in forward
[rank0]:     return LayerNormFunction.apply(x, self.weight, self.bias, self.eps)
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/torch/autograd/function.py", line 574, in apply
[rank0]:     return super().apply(*args, **kwargs)  # type: ignore[misc]
[rank0]:   File "/kaggle/working/colormnet/model/resnet.py", line 258, in forward
[rank0]:     y = weight.view(1, C, 1, 1) * y + bias.view(1, C, 1, 1)
[rank0]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 66.00 MiB. GPU 0 has a total capacity of 14.74 GiB of which 28.12 MiB is free. Process 4776 has 14.71 GiB memory in use. Of the allocated memory 13.83 GiB is allocated by PyTorch, and 427.36 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
wandb: 🚀 View run DINOv2FeatureV6_LocalAtten_DAVISVidevo_s2 at: https://wandb.ai/trong-ldwork-hanoi-university-of-science-and-technology/ColorMNet/runs/yjk2vics
wandb: Find logs at: save_path/wandb/run-20241119_061237-yjk2vics/logs
E1119 06:12:56.618000 137423472170816 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 0 (pid: 684) of binary: /opt/conda/bin/python
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 905, in <module>
    main()
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 901, in main
    run(args)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-11-19_06:12:56
  host      : 378a35f27c4d
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 684)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
```

**Comment by yyang181** [comment]
Hi @trongldwork,

The simplest way is to reduce the batch size from 2 to 1. Please refer to the following link for the configuration:
https://github.com/yyang181/colormnet/blob/c2d2c11043bcbbf22b3018bc4024fdfd8112d466/util/configuration.py#L33

Based on my experience, setting the batch size to 2 requires approximately 24 GB of GPU memory during training on an NVIDIA RTX 4090.

**Comment by trongldwork** [comment]
> Hi @trongldwork,
> 
> The simplest way is to reduce the batch size from 2 to 1. Please refer to the following link for the configuration:
> 
> https://github.com/yyang181/colormnet/blob/c2d2c11043bcbbf22b3018bc4024fdfd8112d466/util/configuration.py#L33
> 
> Based on my experience, setting the batch size to 2 requires approximately 24 GB of GPU memory during training on an NVIDIA RTX 4090.

yes, but after change batch to 1, i still not enough.
Therefore, i see that with both batch 1 or 2, i still break the code when do_val() executed, then i modify code to skip do_val when do_pass, it train perfectly with about 11.5 gb ram, i also tried to reduce size of my validation set, but it still out of memory. Without validation, i cant get my best model, so i think we have some problem in do_val() method code

link_code: https://colab.research.google.com/drive/1QQW8fBnyBIyX_hMV6NCUOwRgrj2aibb4?usp=sharing

**Comment by trongldwork** [comment]
help me pls

**Comment by yyang181** [comment]
> help me pls

Hi @trongldwork, 

It appears that the excessive memory usage during validation could be the culprit. Here are two potential solutions to consider:

1. Reducing the Validation Set Size: One approach is to use a smaller validation set. For instance, instead of using every frame from each video, you could select every n-th frame (e.g., frame 1, frame 5, etc.) for validation. This would significantly reduce the amount of data being processed at once, thereby lowering memory consumption.

2. Checkpointing During Training: Another strategy is to save checkpoints during the training process and then test these saved checkpoints after training is complete. This way, you can evaluate the performance of different checkpoints and select the one that yields the best results without the need to maintain a large validation set throughout the training process.

Feel free to let me know if you have any questions or if you'd like further clarification on these suggestions.

**Comment by trongldwork** [comment]
> > help me pls
> 
> Hi @trongldwork,
> 
> It appears that the excessive memory usage during validation could be the culprit. Here are two potential solutions to consider:
> 
> 1. Reducing the Validation Set Size: One approach is to use a smaller validation set. For instance, instead of using every frame from each video, you could select every n-th frame (e.g., frame 1, frame 5, etc.) for validation. This would significantly reduce the amount of data being processed at once, thereby lowering memory consumption.
> 2. Checkpointing During Training: Another strategy is to save checkpoints during the training process and then test these saved checkpoints after training is complete. This way, you can evaluate the performance of different checkpoints and select the one that yields the best results without the need to maintain a large validation set throughout the training process.
> 
> Feel free to let me know if you have any questions or if you'd like further clarification on these suggestions.

tks you, does it have any config for me for solutions 1 in train.py or other files?
By the way, i'm confused about using examplar image, if exampler is not too much likely the original first frame, it give me a less accurate colorization. By using multiple exampler i see that it's mapping by the frame after sort examplers by name, so incorrect colorized frame increase, do you have any advice or instruction to how to use single and multiple exampler for me
